### ISSUE TITLE
兼容 openresty/luajit2 么

### ISSUE THREAD

**Issue by fanybook** [xingheliufang/go-luajit#1]
如题

**Comment by xingheliufang** [comment]
是兼容的，我在自己的环境里使用的就是openresty的版本，在我的理解里，openresty和原版本在接口层面差异不大，只是多加入了一些方法；这个东西最早也是尝试做一个类似于openresty的网关，本来是想基于gin与luajit，但实际上golang的携程与lua的携程差异比较大，很难糅在一起，故放弃💀

**Comment by fanybook** [comment]
fiber 做网关呢，luajit 也支持协程么

**Comment by xingheliufang** [comment]
web框架是可替换的，选择用哪一个都可以，基本思路是将Go的web框架封装后暴露给lua，之后就可以编写lua脚本控制请求的处理逻辑；lua中也有coroutine的概念，不过在使用时需要手动让出当前协程的执行，和Go的协程调度逻辑有很大的区别

**Comment by fanybook** [comment]
openresty 里写 lua 可以用协程么，我也是刚接触 lua😂

**Comment by xingheliufang** [comment]
openresty我也研究不深, 不过openresty确实重写了lua协程让出和启动的方法, 使他可以和Nginx的IO多路复用逻辑兼容

**Comment by fanybook** [comment]
你这个绑定，做完了么

现在 golang 在 goroutine 里调 lua 虚拟机，lua 内部协不协程，对 golang 没影响吧，lua 没执行完，就相当于阻塞了goroutine，就交由 GMP 调度了吧

**Comment by xingheliufang** [comment]
binding中的函数都是可以用的，main.go里有写示例；确实可以每个goroutine独占一个lua虚拟机，但这个开销有一点大，不是一个好的方案

**Comment by fanybook** [comment]
你要 lua 协程，也被 GMP 管理么？

**Comment by xingheliufang** [comment]
主要的问题是lua的虚拟机本身不是线程安全的，多个goroutine间不应该共享一个lua虚拟机的协程，nginx之所以能这么做，主要是因为他的实现为单线程，不会有并发问题

**Comment by fanybook** [comment]
非线程安全，那加锁呢

**Comment by xingheliufang** [comment]
单协程自然不会有并发问题，但是这样的实现就完全放弃了golang的特点；自己管理调度的话，为什么不选择其他语言呢
